server:
   port: 8988



spring:
  cloud:
    config:
      server:
         git: 
           uri: https://github.com/GaneshKona777/spring-cloud-config-store
           search-paths:
            - '*service'